[package]
name = "lox"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
authors = ["grapple228 <greenapple228882@yandex.ru>"]
readme = "readme.md"
repository = "https://github.com/grapple228/lox_interpreter.git"

[lints.rust]
# unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
rand = "0.10.1"
# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bench]]
name = "scanner_bench"
harness = false

[profile.release]
strip = true           # удалить debug-символы
lto = true             # link-time optimization
# opt-level = "z"        # оптимизация на размер
codegen-units = 1      # больше оптимизаций

[profile.bench]
strip = true           # удалить debug-символы
lto = true             # link-time optimization
# opt-level = "z"        # оптимизация на размер
codegen-units = 1      # больше оптимизаций
